name: Test-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:report

      - name: Rename and Move report to docs 
        run: | 
            mkdir -p docs
            mv newman/newman-run-report.html docs/index.html
    
      - name: Commit and push results
        run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add docs/index.html
            git commit -m "Add test results"
            git push origin main

